In [2]:
import numpy as np 

In [25]:
my_vector = np.arange(10)
my_2D_array = np.arange(10).reshape((2,5))
my_3D_array = np.arange(24).reshape((2,3,4))

In [26]:
my_vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_2D_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
np.transpose(my_vector)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.transpose(my_2D_array)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [31]:
np.transpose(my_3D_array)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [32]:
my_vector.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
my_vector.shape=(1,10)
my_vector

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
np.transpose(my_vector)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [41]:
result = np.transpose(my_3D_array,axes=(2,1,0))
result

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [40]:
my_3D_array.shape, result.shape

((2, 3, 4), (4, 2, 3))

In [53]:
moved = np.swapaxes(my_3D_array,0,1)
moved

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [54]:
moved.shape, my_3D_array.shape

((3, 2, 4), (2, 3, 4))