In [4]:
import numpy as np

In [12]:
#step 2
def create_rubik():
    return np.array([[[i] * 3 for _ in range(3)] for i in range(6)])

In [10]:
def display_rubic(cube):
    faces = ["White", "Yellow", "Green", "Red", "Orange"]
    for i, face in enumerate(cube):
        print(f"{faces[i]} Face:\n {face}\n")

In [11]:
rubik = create_rubik()
display_rubic(rubik)

White Face:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Yellow Face:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Green Face:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]

Red Face:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]

Orange Face:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]



IndexError: list index out of range