In [1]:
import numpy as np

In [2]:
def caculate_square_area(x):
    return x**2

In [6]:
caculate_square_area

<function __main__.caculate_square_area(x)>

In [9]:
np.testing.assert_equal(caculate_square_area(5), 25)

In [11]:
np_func = np.frompyfunc(caculate_square_area,1,1)
np_func

<ufunc 'caculate_square_area (vectorized)'>

In [12]:
caculate_square_area(4)

16

In [23]:
a = np.arange(10)
# caculate_square_area(a)
np_func(a)

array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=object)

In [21]:
b = np.outer(a,a)
b

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [24]:
np_func(b)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 4, 9, 16, 25, 36, 49, 64, 81],
       [0, 4, 16, 36, 64, 100, 144, 196, 256, 324],
       [0, 9, 36, 81, 144, 225, 324, 441, 576, 729],
       [0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296],
       [0, 25, 100, 225, 400, 625, 900, 1225, 1600, 2025],
       [0, 36, 144, 324, 576, 900, 1296, 1764, 2304, 2916],
       [0, 49, 196, 441, 784, 1225, 1764, 2401, 3136, 3969],
       [0, 64, 256, 576, 1024, 1600, 2304, 3136, 4096, 5184],
       [0, 81, 324, 729, 1296, 2025, 2916, 3969, 5184, 6561]],
      dtype=object)