In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b = np.arange(13,25).reshape((3,4))
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [5]:
result0 = np.concatenate((a,b),axis=0)
result0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [6]:
result1 = np.concatenate((a,b), axis=1)
result1

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

In [7]:
stack0 = np.stack((a,b),axis=0)
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [8]:
stack1 = np.stack((a,b),axis=1)
stack1

array([[[ 0,  1,  2,  3],
        [13, 14, 15, 16]],

       [[ 4,  5,  6,  7],
        [17, 18, 19, 20]],

       [[ 8,  9, 10, 11],
        [21, 22, 23, 24]]])

In [12]:
stack2 = np.stack((a,b),axis=2)
stack2

array([[[ 0, 13],
        [ 1, 14],
        [ 2, 15],
        [ 3, 16]],

       [[ 4, 17],
        [ 5, 18],
        [ 6, 19],
        [ 7, 20]],

       [[ 8, 21],
        [ 9, 22],
        [10, 23],
        [11, 24]]])

In [14]:
e = np.random.randint(1,99,size=40).reshape(4,2,5)
e

array([[[28, 77, 18,  7, 98],
        [40, 46, 79, 17, 86]],

       [[42, 36, 41, 15, 12],
        [71, 22, 12, 48, 73]],

       [[46, 26, 29, 28, 46],
        [97, 79, 38, 56, 51]],

       [[43, 30, 93, 39, 59],
        [73, 12,  9, 77, 84]]])

In [29]:
split0 = np.split(e,4,axis=0)
split1 = np.split(e,2,axis=1)
split2 = np.split(e,5,axis=2)

In [23]:
split0

[array([[[28, 77, 18,  7, 98],
         [40, 46, 79, 17, 86]]]),
 array([[[42, 36, 41, 15, 12],
         [71, 22, 12, 48, 73]]]),
 array([[[46, 26, 29, 28, 46],
         [97, 79, 38, 56, 51]]]),
 array([[[43, 30, 93, 39, 59],
         [73, 12,  9, 77, 84]]])]

In [26]:
split1

[array([[[28, 77, 18,  7, 98]],
 
        [[42, 36, 41, 15, 12]],
 
        [[46, 26, 29, 28, 46]],
 
        [[43, 30, 93, 39, 59]]]),
 array([[[40, 46, 79, 17, 86]],
 
        [[71, 22, 12, 48, 73]],
 
        [[97, 79, 38, 56, 51]],
 
        [[73, 12,  9, 77, 84]]])]

In [30]:
split2

[array([[[28],
         [40]],
 
        [[42],
         [71]],
 
        [[46],
         [97]],
 
        [[43],
         [73]]]),
 array([[[77],
         [46]],
 
        [[36],
         [22]],
 
        [[26],
         [79]],
 
        [[30],
         [12]]]),
 array([[[18],
         [79]],
 
        [[41],
         [12]],
 
        [[29],
         [38]],
 
        [[93],
         [ 9]]]),
 array([[[ 7],
         [17]],
 
        [[15],
         [48]],
 
        [[28],
         [56]],
 
        [[39],
         [77]]]),
 array([[[98],
         [86]],
 
        [[12],
         [73]],
 
        [[46],
         [51]],
 
        [[59],
         [84]]])]

In [27]:
type(split1)

list

In [28]:
e.shape

(4, 2, 5)