In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(12).reshape((3,4))

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.tile(a, 3).reshape(3,a.size)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
np.tile(a,(2,2,2)).shape

(2, 2, 20)

In [14]:
np.tile(b,2)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [16]:
np.repeat(a,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [23]:
np.repeat(b,2,axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [24]:
c = np.random.randint(0, 99, size=10)
d = np.random.randint(0, 99, size=(3,4))

In [25]:
c

array([68, 77, 63, 12, 46, 16, 95, 65, 59, 37])

In [26]:
d

array([[36, 95, 76, 87],
       [14, 68, 87,  4],
       [11, 20,  3, 12]])

In [27]:
np.sort(c)

array([12, 16, 37, 46, 59, 63, 65, 68, 77, 95])

In [30]:
np.sort(d, axis=1)

array([[36, 76, 87, 95],
       [ 4, 14, 68, 87],
       [ 3, 11, 12, 20]])

In [31]:
np.argsort(c)

array([3, 5, 9, 4, 8, 2, 7, 0, 1, 6], dtype=int64)

In [34]:
np.argsort(d, axis=0)

array([[2, 2, 2, 1],
       [1, 1, 0, 2],
       [0, 0, 1, 0]], dtype=int64)

In [35]:
np.argmax(c)

6

In [36]:
np.argmin(c)

3

In [37]:
np.argmax(d)

1

In [40]:
np.argmin(d, axis=0)

array([2, 2, 2, 1], dtype=int64)