In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.append(a,(10,11))
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = np.random.randint(1,99,size=(2,3,4))
c

array([[[41, 95, 61, 41],
        [50,  9, 90, 72],
        [23, 73,  8,  4]],

       [[ 3, 74, 69, 45],
        [69, 83, 27, 30],
        [88, 25, 97, 65]]])

In [10]:
g = np.random.randint(1,99,size=(2,3,4))
d = np.append(c,g,axis=2)
d

array([[[41, 95, 61, 41, 60, 63, 86,  6],
        [50,  9, 90, 72, 33, 10, 14, 19],
        [23, 73,  8,  4, 11, 35, 56, 77]],

       [[ 3, 74, 69, 45, 68, 85, 13, 31],
        [69, 83, 27, 30, 19, 22, 40, 23],
        [88, 25, 97, 65, 74, 80, 87, 96]]])

In [11]:
d.shape

(2, 3, 8)

In [12]:
g.shape

(2, 3, 4)

In [13]:
c.shape

(2, 3, 4)

In [18]:
h = np.insert(c, 2, 10, axis=2)
h

array([[[41, 95, 10, 61, 41],
        [50,  9, 10, 90, 72],
        [23, 73, 10,  8,  4]],

       [[ 3, 74, 10, 69, 45],
        [69, 83, 10, 27, 30],
        [88, 25, 10, 97, 65]]])

In [20]:
v = np.empty((2,3,4))
v

array([[[4.67296746e-307, 1.69121096e-306, 2.13621350e-306,
         2.22523004e-306],
        [1.29061142e-306, 1.42419938e-306, 7.56603881e-307,
         8.45603440e-307],
        [3.56043054e-307, 1.60219306e-306, 6.23059726e-307,
         1.06811422e-306]],

       [[3.56043054e-307, 1.37961641e-306, 1.00132483e-307,
         8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
         1.33510679e-306],
        [2.22522597e-306, 1.11260144e-306, 6.89812281e-307,
         2.22522596e-306]]])

In [21]:
np.copyto(v,c)
v

array([[[41., 95., 61., 41.],
        [50.,  9., 90., 72.],
        [23., 73.,  8.,  4.]],

       [[ 3., 74., 69., 45.],
        [69., 83., 27., 30.],
        [88., 25., 97., 65.]]])

In [30]:
m=np.delete(c, 3, axis=2)
m

array([[[41, 95, 61],
        [50,  9, 90],
        [23, 73,  8]],

       [[ 3, 74, 69],
        [69, 83, 27],
        [88, 25, 97]]])