In [13]:
import numpy as np

In [22]:
a = np.random.randint(1,100,size=(1,60))
a

array([[86, 89, 37, 42, 77, 83, 77, 39, 14, 48, 15, 50,  1, 96, 75, 86,
        87,  5, 70, 46, 14, 76, 92, 18, 72, 77,  3, 16, 42, 11, 53,  4,
        47, 36, 40, 72, 37, 92, 20,  2, 73, 12, 25, 87, 68, 16, 17, 68,
        32, 61, 31, 58,  4, 53, 13, 41, 55, 55, 51, 39]])

In [9]:
a.shape

(1, 60)

In [24]:
a.reshape(1,60)

array([[86, 89, 37, 42, 77, 83, 77, 39, 14, 48, 15, 50,  1, 96, 75, 86,
        87,  5, 70, 46, 14, 76, 92, 18, 72, 77,  3, 16, 42, 11, 53,  4,
        47, 36, 40, 72, 37, 92, 20,  2, 73, 12, 25, 87, 68, 16, 17, 68,
        32, 61, 31, 58,  4, 53, 13, 41, 55, 55, 51, 39]])

In [35]:
a = a.reshape(2,6,5)
a

array([[[86, 89, 37, 42, 77],
        [83, 77, 39, 14, 48],
        [15, 50,  1, 96, 75],
        [86, 87,  5, 70, 46],
        [14, 76, 92, 18, 72],
        [77,  3, 16, 42, 11]],

       [[53,  4, 47, 36, 40],
        [72, 37, 92, 20,  2],
        [73, 12, 25, 87, 68],
        [16, 17, 68, 32, 61],
        [31, 58,  4, 53, 13],
        [41, 55, 55, 51, 39]]])

In [36]:
greatter_than_30 = a>30
greatter_than_30

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True, False,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False,  True,  True],
        [False,  True,  True, False,  True],
        [ True, False, False,  True, False]],

       [[ True, False,  True,  True,  True],
        [ True,  True,  True, False, False],
        [ True, False, False,  True,  True],
        [False, False,  True,  True,  True],
        [ True,  True, False,  True, False],
        [ True,  True,  True,  True,  True]]])

In [37]:
a[greatter_than_30]

array([86, 89, 37, 42, 77, 83, 77, 39, 48, 50, 96, 75, 86, 87, 70, 46, 76,
       92, 72, 77, 42, 53, 47, 36, 40, 72, 37, 92, 73, 87, 68, 68, 32, 61,
       31, 58, 53, 41, 55, 55, 51, 39])

In [38]:
even_elements = a%2==0
even_elements

array([[[ True, False, False,  True, False],
        [False, False, False,  True,  True],
        [False,  True, False,  True, False],
        [ True, False, False,  True,  True],
        [ True,  True,  True,  True,  True],
        [False, False,  True,  True, False]],

       [[False,  True, False,  True,  True],
        [ True, False,  True,  True,  True],
        [False,  True, False, False,  True],
        [ True, False,  True,  True, False],
        [False,  True,  True, False, False],
        [False, False, False, False, False]]])

In [39]:
a[even_elements]

array([86, 42, 14, 48, 50, 96, 86, 70, 46, 14, 76, 92, 18, 72, 16, 42,  4,
       36, 40, 72, 92, 20,  2, 12, 68, 16, 68, 32, 58,  4])

In [40]:
final_mask = np.logical_and(greatter_than_30,even_elements)
a[final_mask]

array([86, 42, 48, 50, 96, 86, 70, 46, 76, 92, 72, 42, 36, 40, 72, 92, 68,
       68, 32, 58])

In [43]:
less_than_20 = a<20
result = np.logical_or(greatter_than_30,less_than_20)
a[result]

array([86, 89, 37, 42, 77, 83, 77, 39, 14, 48, 15, 50,  1, 96, 75, 86, 87,
        5, 70, 46, 14, 76, 92, 18, 72, 77,  3, 16, 42, 11, 53,  4, 47, 36,
       40, 72, 37, 92,  2, 73, 12, 87, 68, 16, 17, 68, 32, 61, 31, 58,  4,
       53, 13, 41, 55, 55, 51, 39])