In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 99, size=(3,4))
b = np.random.randint(0, 99, size=(3,4))

In [3]:
a

array([[25, 23, 35, 83],
       [89, 93, 26, 91],
       [80, 73, 59, 46]])

In [4]:
b

array([[70,  3, 54, 39],
       [83,  7, 64, 40],
       [92, 26, 16, 74]])

In [5]:
a*b

array([[1750,   69, 1890, 3237],
       [7387,  651, 1664, 3640],
       [7360, 1898,  944, 3404]])

In [9]:
c=np.transpose(b)
c

array([[70, 83, 92],
       [ 3,  7, 26],
       [54, 64, 16],
       [39, 40, 74]])

In [ ]:
d=np.dot(c,a)
e=np.dot(a,c)

array([[16497, 16045, 10036, 17595],
       [ 2778,  2618,  1821,  2082],
       [ 8326,  8362,  4498, 11042],
       [10455, 10019,  6771, 10281]])

In [13]:
d,c

(array([[16497, 16045, 10036, 17595],
        [ 2778,  2618,  1821,  2082],
        [ 8326,  8362,  4498, 11042],
        [10455, 10019,  6771, 10281]]),
 array([[70, 83, 92],
        [ 3,  7, 26],
        [54, 64, 16],
        [39, 40, 74]]))

In [14]:
x = np.dot(a,b.T)
x

array([[ 6946,  7796,  9600],
       [11462, 13342, 17756],
       [10799, 12767, 13606]])