In [1]:
import numpy as np

In [2]:
# creat array, matrix
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1, 2],[3, 4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
# shape
print(a.shape, b.shape)

(4,) (2, 2)


In [6]:
# reshape
c = a.reshape((4,1))

In [7]:
c.shape

(4, 1)

In [8]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [9]:
d

array([[[1],
        [2]],

       [[3],
        [4]]])

In [10]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([4,5])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5])

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a+b
c

array([5, 7, 9])

In [13]:
c = a*b
c

array([ 4, 10, 18])

In [14]:
c = np.array([10])
d = a + c
d

array([11, 12, 13])

In [3]:
a = np.arange(0,21,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
b = np.linspace(0,20,5,retstep=True)
b

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [11]:
c = np.ones((2,3,3),dtype=int)
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [13]:
d = np.zeros((3,3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
e = np.random.random(size=(3,3))
e

array([[0.97932526, 0.17694565, 0.86451035],
       [0.77125558, 0.72891511, 0.28199008],
       [0.09277275, 0.29532644, 0.49937358]])

In [16]:
g = np.random.randint(1,10,(2,3),dtype=int)
g

array([[9, 5, 2],
       [3, 4, 1]])

In [23]:
np.random.seed(1)
t = np.random.randint(1,10,(3,3))
t

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])