In [1]:
import numpy as np

In [ ]:
# باقی مانده تقسیم رو برمیگردونه 
a = np.mod(10,4)
a

2

In [3]:
10 % 8

2

In [5]:
b = np.equal(2,2)
b

True

In [6]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d = np.arange(10,20)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
g = np.outer(s,d)
g

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 144, 153, 162, 171]])

In [11]:
h = np.add(s,d)
h

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
e = np.subtract(s,d)
e

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [13]:
np.multiply(s,d)

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [14]:
np.divide(s,d)

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [15]:
np.add.outer(s,d)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [16]:
np.subtract.outer(s,d)

array([[-10, -11, -12, -13, -14, -15, -16, -17, -18, -19],
       [ -9, -10, -11, -12, -13, -14, -15, -16, -17, -18],
       [ -8,  -9, -10, -11, -12, -13, -14, -15, -16, -17],
       [ -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16],
       [ -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15],
       [ -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14],
       [ -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13],
       [ -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12],
       [ -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10]])

In [17]:
np.multiply.outer(s,d)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 30,  33,  36,  39,  42,  45,  48,  51,  54,  57],
       [ 40,  44,  48,  52,  56,  60,  64,  68,  72,  76],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114],
       [ 70,  77,  84,  91,  98, 105, 112, 119, 126, 133],
       [ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152],
       [ 90,  99, 108, 117, 126, 135, 144, 153, 162, 171]])

In [18]:
np.divide.outer(s,d)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
        0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714,
        0.13333333, 0.125     , 0.11764706, 0.11111111, 0.10526316],
       [0.3       , 0.27272727, 0.25      , 0.23076923, 0.21428571,
        0.2       , 0.1875    , 0.17647059, 0.16666667, 0.15789474],
       [0.4       , 0.36363636, 0.33333333, 0.30769231, 0.28571429,
        0.26666667, 0.25      , 0.23529412, 0.22222222, 0.21052632],
       [0.5       , 0.45454545, 0.41666667, 0.38461538, 0.35714286,
        0.33333333, 0.3125    , 0.29411765, 0.27777778, 0.26315789],
       [0.6       , 0.54545455, 0.5       , 0.46153846, 0.42857143,
        0.4       , 0.375     , 0.35294118, 0.33333333, 0.31578947],
       [0.7       , 0.63636364, 0.5833333

In [32]:
def is_intger(number):
    return np.equal(np.mod(number, 1),0)

In [33]:
np_func = np.frompyfunc(is_intger,1,1)

In [23]:
numbers_range = 9

In [24]:
first_array = np.arange(numbers_range)+1
second_array = np.arange(numbers_range)+1

In [25]:
first_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
second_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
result = np.add.outer(first_array**2, second_array**2)
result

array([[  2,   5,  10,  17,  26,  37,  50,  65,  82],
       [  5,   8,  13,  20,  29,  40,  53,  68,  85],
       [ 10,  13,  18,  25,  34,  45,  58,  73,  90],
       [ 17,  20,  25,  32,  41,  52,  65,  80,  97],
       [ 26,  29,  34,  41,  50,  61,  74,  89, 106],
       [ 37,  40,  45,  52,  61,  72,  85, 100, 117],
       [ 50,  53,  58,  65,  74,  85,  98, 113, 130],
       [ 65,  68,  73,  80,  89, 100, 113, 128, 145],
       [ 82,  85,  90,  97, 106, 117, 130, 145, 162]])

In [29]:
final = np.sqrt(result)
final

array([[ 1.41421356,  2.23606798,  3.16227766,  4.12310563,  5.09901951,
         6.08276253,  7.07106781,  8.06225775,  9.05538514],
       [ 2.23606798,  2.82842712,  3.60555128,  4.47213595,  5.38516481,
         6.32455532,  7.28010989,  8.24621125,  9.21954446],
       [ 3.16227766,  3.60555128,  4.24264069,  5.        ,  5.83095189,
         6.70820393,  7.61577311,  8.54400375,  9.48683298],
       [ 4.12310563,  4.47213595,  5.        ,  5.65685425,  6.40312424,
         7.21110255,  8.06225775,  8.94427191,  9.8488578 ],
       [ 5.09901951,  5.38516481,  5.83095189,  6.40312424,  7.07106781,
         7.81024968,  8.60232527,  9.43398113, 10.29563014],
       [ 6.08276253,  6.32455532,  6.70820393,  7.21110255,  7.81024968,
         8.48528137,  9.21954446, 10.        , 10.81665383],
       [ 7.07106781,  7.28010989,  7.61577311,  8.06225775,  8.60232527,
         9.21954446,  9.89949494, 10.63014581, 11.40175425],
       [ 8.06225775,  8.24621125,  8.54400375,  8.94427191,  9

In [34]:
np_func(final)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False, False],
       [False, False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, False],
       [False, False, False, False, False, False, False, False, False]],
      dtype=object)