In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 4

array([4, 5, 6, 7, 8])

In [4]:
b = np.random.randint(1,9,size=5).reshape((1,5))
b

array([[2, 3, 3, 3, 7]])

In [5]:
a+b

array([[ 2,  4,  5,  6, 11]])

In [6]:
a-b

array([[-2, -2, -1,  0, -3]])

In [7]:
a*b

array([[ 0,  3,  6,  9, 28]])

In [8]:
a/b

array([[0.        , 0.33333333, 0.66666667, 1.        , 0.57142857]])

In [10]:
a**b

array([[    0,     1,     8,    27, 16384]])

In [11]:
a%b

array([[0, 1, 2, 0, 4]])

In [12]:
a//b

array([[0, 0, 0, 1, 0]])

In [17]:
c = np.random.randint(1,99,size=50).reshape((10,5))
c

array([[24,  8,  6, 90, 96],
       [ 9, 63, 12, 20, 90],
       [21, 73, 63, 92,  8],
       [11, 90, 76, 72, 84],
       [56, 81, 93, 41, 34],
       [36, 69, 29,  4, 66],
       [32,  8, 55, 85, 35],
       [18, 94, 75, 14, 62],
       [93, 20, 48, 40, 45],
       [20, 29, 51, 78, 88]])

In [19]:
b

array([[2, 3, 3, 3, 7]])

In [18]:
b+c

array([[ 26,  11,   9,  93, 103],
       [ 11,  66,  15,  23,  97],
       [ 23,  76,  66,  95,  15],
       [ 13,  93,  79,  75,  91],
       [ 58,  84,  96,  44,  41],
       [ 38,  72,  32,   7,  73],
       [ 34,  11,  58,  88,  42],
       [ 20,  97,  78,  17,  69],
       [ 95,  23,  51,  43,  52],
       [ 22,  32,  54,  81,  95]])

In [20]:
d = np.arange(5).reshape((5,1))
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
b+d

array([[ 2,  3,  3,  3,  7],
       [ 3,  4,  4,  4,  8],
       [ 4,  5,  5,  5,  9],
       [ 5,  6,  6,  6, 10],
       [ 6,  7,  7,  7, 11]])

In [23]:
e = np.random.randint(1,99,size=40).reshape((2,5,4))
e

array([[[78,  6, 59, 22],
        [52, 59, 66, 50],
        [60, 57, 88, 11],
        [32, 35, 95,  2],
        [ 7, 29, 74, 91]],

       [[56, 55, 60, 54],
        [78, 42, 25, 70],
        [85, 10, 91, 43],
        [29,  4, 27, 25],
        [70,  2, 64, 98]]])

In [25]:
array = np.arange(20).reshape((5,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
e+array

array([[[ 78,   7,  61,  25],
        [ 56,  64,  72,  57],
        [ 68,  66,  98,  22],
        [ 44,  48, 109,  17],
        [ 23,  46,  92, 110]],

       [[ 56,  56,  62,  57],
        [ 82,  47,  31,  77],
        [ 93,  19, 101,  54],
        [ 41,  17,  41,  40],
        [ 86,  19,  82, 117]]])

In [27]:
e

array([[[78,  6, 59, 22],
        [52, 59, 66, 50],
        [60, 57, 88, 11],
        [32, 35, 95,  2],
        [ 7, 29, 74, 91]],

       [[56, 55, 60, 54],
        [78, 42, 25, 70],
        [85, 10, 91, 43],
        [29,  4, 27, 25],
        [70,  2, 64, 98]]])

In [ ]:
# miangin
np.mean(e)

49.025

In [29]:
# miane
np.median(e)

54.5

In [ ]:
# kamtarin
np.min(e)

2

In [ ]:
# varians(ekhtelaf dade ha ba miangin)
np.var(e)

798.6743749999999

In [ ]:
# enheraf meiar(radical varians)
np.std(e)

28.260827571039034

In [34]:
np.sqrt(np.var(e))

28.260827571039034

In [35]:
np.sum(e)

1961

In [37]:
np.sum(e)/e.size

49.025

In [38]:
sum(e)

array([[134,  61, 119,  76],
       [130, 101,  91, 120],
       [145,  67, 179,  54],
       [ 61,  39, 122,  27],
       [ 77,  31, 138, 189]])

In [40]:
f = np.arange(100)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [41]:
np.sum(f)

4950

In [42]:
sum(f)

4950

In [44]:
my_array = np.random.randint(1,99,size=1000000)

In [45]:
np.sum(my_array)

49471247

In [46]:
sum(my_array)

49471247

In [49]:
import datetime

python_start = datetime.datetime.now()
result = sum(my_array)
python_end = datetime.datetime.now()
time_python = python_end - python_start
time_python

datetime.timedelta(microseconds=118484)

In [50]:
python_start = datetime.datetime.now()
result = np.sum(my_array)
python_end = datetime.datetime.now()
time_python = python_end - python_start
time_python

datetime.timedelta(microseconds=1260)