In [1]:
import numpy as np

In [3]:
a = np.arange(1, 21, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
b = np.linspace(0, 20, 8, retstep=True)
b

(array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
        14.28571429, 17.14285714, 20.        ]),
 2.857142857142857)

In [9]:
c = np.ones((3, 2, 2), dtype=int)
c

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [11]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
e = np.random.random((2,2))
e

array([[0.70880414, 0.60595543],
       [0.81821557, 0.72736075]])

In [16]:
g = np.random.randint(1, 10, (2, 3, 4), dtype=int)
g

array([[[1, 7, 7, 8],
        [2, 7, 1, 3],
        [3, 9, 8, 5]],

       [[7, 7, 9, 8],
        [1, 3, 4, 9],
        [4, 4, 2, 7]]])

In [27]:
np.random.seed(1)
t = np.random.randint(1, 10, (2, 3))
t

array([[6, 9, 6],
       [1, 1, 2]])