In [1]:
import numpy as np

In [2]:
a = np.arange(1, 16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
a[1]

2

In [4]:
a[-2]

14

In [5]:
a[1]=150

In [6]:
a

array([  1, 150,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [8]:
b = np.arange(1, 21)
b.shape = (4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
b[1]

array([ 6,  7,  8,  9, 10])

In [10]:
b[1][2]

8

In [11]:
b[:, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [13]:
c = np.random.randint(1, 9, size=(2, 3, 4))
c

array([[[8, 3, 2, 8],
        [2, 4, 6, 4],
        [3, 6, 2, 2]],

       [[5, 8, 3, 8],
        [5, 3, 6, 1],
        [3, 2, 6, 1]]])

In [14]:
c[0]

array([[8, 3, 2, 8],
       [2, 4, 6, 4],
       [3, 6, 2, 2]])

In [16]:
c[0][1]

array([2, 4, 6, 4])

In [17]:
c[1, 2, 3]

1

In [20]:
c[:,:, 2:4]

array([[[2, 8],
        [6, 4],
        [2, 2]],

       [[3, 8],
        [6, 1],
        [6, 1]]])