In [12]:
import numpy as np 

In [3]:
a = np.arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [4]:
a.shape

(60,)

In [5]:
a = a.reshape((1,60))
a.shape

(1, 60)

In [6]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [8]:
a = a.reshape((2,5,6))
a

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]]])

In [11]:
a = np.random.randint(1,100,size=60)
a

array([15, 32, 37, 36, 47, 54, 23,  1,  9, 97, 88, 14, 58, 85, 67, 39, 80,
       31, 61, 31, 78, 37, 64, 12, 73, 80, 29, 65, 30, 36, 56,  2, 54, 13,
       58, 72, 51, 61,  6, 87, 18,  2, 45, 24, 45, 12, 83, 55, 38,  1, 15,
       49, 57, 79, 44,  6, 11, 23, 64, 29])

In [13]:
u = np.unique(a)
u

array([ 1,  2,  6,  9, 11, 12, 13, 14, 15, 18, 23, 24, 29, 30, 31, 32, 36,
       37, 38, 39, 44, 45, 47, 49, 51, 54, 55, 56, 57, 58, 61, 64, 65, 67,
       72, 73, 78, 79, 80, 83, 85, 87, 88, 97])

In [14]:
a[a>22]

array([32, 37, 36, 47, 54, 23, 97, 88, 58, 85, 67, 39, 80, 31, 61, 31, 78,
       37, 64, 73, 80, 29, 65, 30, 36, 56, 54, 58, 72, 51, 61, 87, 45, 24,
       45, 83, 55, 38, 49, 57, 79, 44, 23, 64, 29])

In [15]:
a_30 = a > 30
a_30

array([False,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False, False,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False, False, False,  True, False])

In [16]:
even_elements = a%2==0
even_elements

array([False,  True, False,  True, False,  True, False, False, False,
       False,  True,  True,  True, False, False, False,  True, False,
       False, False,  True, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False,  True, False,  True,  True, False,  True, False,
        True, False, False,  True, False, False, False, False, False,
        True,  True, False, False,  True, False])

In [19]:
final_mask = np.logical_and(a_30, even_elements)
a[final_mask]


array([32, 36, 54, 88, 58, 80, 78, 64, 80, 36, 56, 54, 58, 72, 38, 44, 64])

In [20]:
less_than_20 = a < 20
result = np.logical_or(a_30,less_than_20)
a[result]

array([15, 32, 37, 36, 47, 54,  1,  9, 97, 88, 14, 58, 85, 67, 39, 80, 31,
       61, 31, 78, 37, 64, 12, 73, 80, 65, 36, 56,  2, 54, 13, 58, 72, 51,
       61,  6, 87, 18,  2, 45, 45, 12, 83, 55, 38,  1, 15, 49, 57, 79, 44,
        6, 11, 64])