In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
a.shape #تعداد سطر و ستون

(3,)

In [5]:
a.ndim # تعداد بعد

1

In [4]:
a.dtype #نوع بیت 

dtype('int32')

In [5]:
a.size #تعداد عناصر آرایه

3

In [6]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [11]:
b.dtype

dtype('int32')

In [12]:
b.size

6

In [13]:
c = np.array([[1.2, 2, 3.3],
              [4, 5.1, 6]])
c

array([[1.2, 2. , 3.3],
       [4. , 5.1, 6. ]])

In [14]:
c.shape

(2, 3)

In [15]:
c.dtype

dtype('float64')

In [16]:
c.ndim

2

In [17]:
c.size

6

In [19]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[7, 8, 9], [10,11,12]])
f = np.array([d, e])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
f.shape

(2, 2, 3)

In [21]:
d.shape

(2, 3)

In [22]:
f.dtype

dtype('int32')

In [23]:
f.ndim

3

In [24]:
f.size

12

In [25]:
type(a)


numpy.ndarray

In [26]:
type(b)

numpy.ndarray

In [27]:
type(c)

numpy.ndarray

In [28]:
type(f)

numpy.ndarray