In [1]:
import numpy as np

In [ ]:
#film5
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [7]:
a.ndim

1

In [8]:
a.dtype

dtype('int32')

In [10]:
a.size

3

In [12]:
b = np.array([[1, 2, 3],
             [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [14]:
b.ndim

2

In [15]:
b.dtype

dtype('int32')

In [16]:
b.size

6

In [23]:
c = np.array([[1.1, 2.5, 3.2],
              [4j, 5, 6.8]])
c

array([[1.1+0.j, 2.5+0.j, 3.2+0.j],
       [0. +4.j, 5. +0.j, 6.8+0.j]])

In [18]:
c.shape

(2, 3)

In [19]:
c.ndim

2

In [24]:
c.dtype

dtype('complex128')

In [25]:
c.size

6

In [26]:
d = np.array([[1, 2.2, 3],[4, 5, 6]])
e = np.array([[4.2, 5.7, 6],[7, 8, 9]])
f = np.array([d,e])
f

array([[[1. , 2.2, 3. ],
        [4. , 5. , 6. ]],

       [[4.2, 5.7, 6. ],
        [7. , 8. , 9. ]]])

In [27]:
f.shape


(2, 2, 3)

In [28]:
f.ndim

3

In [29]:
f.dtype

dtype('float64')

In [30]:
f.size

12

In [31]:
type(a)

numpy.ndarray

In [32]:
type(b)

numpy.ndarray

In [33]:
type(c)

numpy.ndarray

In [35]:
#film6

In [36]:
a = np.arange(0, 21, 2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
b = np.linspace(0, 20, 5, retstep=True)
b

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [45]:
c = np.ones((2, 2, 3), dtype=int)
c

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [46]:
d = np.zeros((2, 3, 4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [55]:
e = np.random.random((2,2,3))
e

array([[[0.33749777, 0.32547076, 0.90667115],
        [0.38192643, 0.18571195, 0.68083967]],

       [[0.44953166, 0.12359702, 0.1150225 ],
        [0.2601729 , 0.94348133, 0.16507328]]])

In [54]:
f = np.random.randint(1, 5, (2,2,3))
f

array([[[3, 2, 2],
        [1, 4, 3]],

       [[3, 2, 1],
        [1, 4, 2]]])

In [60]:
np.random.seed(1)
g = np.random.randint(1,9,(2,2,2))
g

array([[[6, 4],
        [5, 1]],

       [[8, 2],
        [4, 6]]])

In [61]:
#film7

In [63]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
a[0]

1

In [65]:
a[1]

2

In [66]:
a[-1]

14

In [68]:
b = np.arange(1,11)
b.shape = (2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
b[1]

array([ 6,  7,  8,  9, 10])

In [70]:
b[(1,1)]

7

In [71]:
b[0,0]

1

In [73]:
b[:,1]

array([2, 7])

In [75]:
b[:,0:1]

array([[1],
       [6]])

In [76]:
c = np.random.randint(1, 10, (2, 3, 3))
c

array([[[1, 1, 2],
        [8, 7, 3],
        [5, 6, 3]],

       [[5, 3, 5],
        [8, 8, 2],
        [8, 1, 7]]])

In [77]:
c[0]


array([[1, 1, 2],
       [8, 7, 3],
       [5, 6, 3]])

In [78]:
c[0][1]

array([8, 7, 3])

In [81]:
c[1][1]

array([8, 8, 2])

In [82]:
c[1][1][1]

8

In [83]:
c[1,1,1]

8

In [84]:
c

array([[[1, 1, 2],
        [8, 7, 3],
        [5, 6, 3]],

       [[5, 3, 5],
        [8, 8, 2],
        [8, 1, 7]]])

In [88]:
c[:,:,0:2]


array([[[1, 1],
        [8, 7],
        [5, 6]],

       [[5, 3],
        [8, 8],
        [8, 1]]])

In [1]:
# masked

In [3]:
import numpy as np

In [7]:
x = np.arange(1, 10, 2)
x

array([1, 3, 5, 7, 9])

In [22]:
z = np.random.randint(1, 10, (2,2))
z

array([[4, 7],
       [1, 5]])

In [26]:
z[0][1]

7

In [25]:
z[1]

array([1, 5])