In [1]:
import numpy as np

In [2]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
a[0]

1

In [4]:
a[-2]

14

In [6]:
a[2] = 20
a

array([ 1,  2, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
b = np.arange(1,21)
b.shape = (4,5)
b
b.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
b[1]

array([ 6,  7,  8,  9, 10])

In [14]:
b[1][1]

7

In [15]:
b[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [16]:
c = np.random.randint(1, 9, size=(2,3,4))
c

array([[[5, 2, 1, 7],
        [3, 5, 3, 8],
        [8, 8, 2, 1]],

       [[2, 2, 7, 2],
        [7, 6, 4, 8],
        [5, 4, 5, 8]]])

In [17]:
c[0]

array([[5, 2, 1, 7],
       [3, 5, 3, 8],
       [8, 8, 2, 1]])

In [18]:
c[0][1]

array([3, 5, 3, 8])

In [19]:
c[1][1][1]

6

In [24]:
c[:,:,-2:-1]

array([[[1],
        [3],
        [2]],

       [[7],
        [4],
        [5]]])

In [26]:
d = np.random.randint(1,10,size=(2,2,3,5))
d

array([[[[9, 3, 4, 7, 3],
         [2, 3, 7, 8, 9],
         [8, 3, 1, 7, 9]],

        [[3, 7, 9, 4, 9],
         [9, 8, 4, 8, 3],
         [4, 6, 4, 7, 4]]],


       [[[9, 6, 3, 4, 6],
         [2, 4, 7, 7, 5],
         [9, 8, 9, 3, 3]],

        [[5, 5, 3, 2, 4],
         [8, 6, 9, 4, 1],
         [7, 8, 2, 2, 9]]]])

In [28]:
d.ndim

4